### ISSUE TITLE
Spoilers

### ISSUE THREAD

**Issue by CFLombardi** [CFLombardi/sethBot#33]
I would like to implement syntax that we can use to obfuscate messages and require the viewer to click on a link that would reveal the message.  This would allow users to post spoilers on content and but the onus on the viewer to view it rather than it being out there in the open.

**Comment by Kydane** [comment]
This is actually getting a bit of buzz on this exact topic in the discord suggestion box forums. 
Currently, there is no way to manage showing something one way for a user but a different way for another user. 
The only way this could be done (with the current discord app) is to create a link that launches a separate window with the hidden message. that text would need to be hosted by the server

**Comment by CFLombardi** [comment]
What about this?

https://www.npmjs.com/package/discord-spoiler-bot

**Comment by Kydane** [comment]
I think you'll get flack for using something like this because it just uses a gif under the hood to "hide" something. On mobile, gifs plays by default so this isn't going to work and i'm fairly certain that you can have discord always run gifs by default (not requiring you to need to scroll over).
If implemented as described, half the users are going to be like "wtf this is useless"

**Comment by Kydane** [comment]
> Known issues
>    It's been reported that GIFs play continuously on mobile devices instead of stopping after revealing the spoiler. Sadly this is a limitation of the mobile Discord app and I can't do anything about it.
via the library notes

**Comment by CFLombardi** [comment]
I'm wondering if we can register "on click" events with a message?

**Comment by CFLombardi** [comment]
Discord has implemented the functionality for us!  Hooray discord!
